---
format_version: '11'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: react-native

workflows:
  deploy:
    description: Build Abisinya Bingo - Professional React Native Bingo App (Fixed - No EAS)
    steps:
    - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@8: {}
    - npm@1:
        inputs:
        - command: install
        - cache_local_deps: 'no'
    - npm@1:
        inputs:
        - command: test
    - deploy-to-bitrise-io@2:
        inputs:
        - deploy_path: '.'
        - notify_user_groups: none
    - script@1:
        title: Create Simple App Package
        inputs:
        - content: |
            #!/bin/bash
            set -ex
            
            echo "🚀 Creating Abisinya Bingo App Package"
            
            # Create build directory
            mkdir -p ./abisinya-bingo-build
            
            # Create a simple app package with just the essential files
            echo "📦 Copying essential app files..."
            
            # Copy main app files
            cp App.tsx ./abisinya-bingo-build/ 2>/dev/null || echo "App.tsx not found"
            cp package.json ./abisinya-bingo-build/ 2>/dev/null || echo "package.json not found"
            cp app.json ./abisinya-bingo-build/ 2>/dev/null || echo "app.json not found"
            cp index.js ./abisinya-bingo-build/ 2>/dev/null || echo "index.js not found"
            
            # List what we actually copied
            echo "📋 Files in build directory:"
            ls -la ./abisinya-bingo-build/
            
            echo "✅ App package created successfully!"

app:
  envs:
  - opts:
      is_expand: false
    NPM_CONFIG_LEGACY_PEER_DEPS: 'true'
  - opts:
      is_expand: false
    NPM_CONFIG_FORCE: 'true'
  - opts:
      is_expand: false
    NODE_VERSION: '20'